// program to demonstrate Run time Error

public class P41 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		System.out.println("main starts");
		try
		{
			int res=2/0;
			System.out.println("res="+res);
		}
		catch(ArithmeticException e)
		{
			System.out.println("Exception caught"+e);
		}
		System.out.println("main ends");
	}

}

********************output********************************
main starts
Exception caughtjava.lang.ArithmeticException: / by zero
main ends